Update apiTest.yaml

diff --git a/.github/workflows/apiTest.yaml b/.github/workflows/apiTest.yaml
--- a/.github/workflows/apiTest.yaml
+++ b/.github/workflows/apiTest.yaml
@@ -49,9 +49,19 @@ jobs:
   #  - name: Make REST request
    #   run: |
   #      curl -X GET http://localhost:5000/ping
+    - name: Install Newman
+      run: npm install -g newman
+
+    #- name: Run API tests
+     # run: |
+      #    postman collection run "${{ github.workspace }}/postman/collections/tests.json" -e "20887326-37b84bc2-f993-415e-b8b0-c72f2e85e26e" --integration-id "138020-${{ github.run_id }}" --bail
     - name: Run API tests
       run: |
-          postman collection run "${{ github.workspace }}/postman/collections/tests.json" -e "20887326-37b84bc2-f993-415e-b8b0-c72f2e85e26e" --integration-id "138020-${{ github.run_id }}" --bail
+         newman run "${{ github.workspace }}/postman/collections/tests.json" -e "20887326-37b84bc2-f993-415e-b8b0-c72f2e85e26e" --bail
+         if [ $? -ne 0 ]; then
+          echo "Newman tests failed"
+          exit 1
+         fi
 
    
     - name: Stop and remove Docker Compose services
