Update apiTest.yaml

diff --git a/.github/workflows/apiTest.yaml b/.github/workflows/apiTest.yaml
--- a/.github/workflows/apiTest.yaml
+++ b/.github/workflows/apiTest.yaml
@@ -71,13 +71,17 @@ jobs:
       run: |
         PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h localhost -p ${{ secrets.DB_PORT }} -U${{ secrets.DB_USERNAME }} -d ${{ secrets.DB_NAME }} -c ${{ secrets.UPDATE_ORGANIZER_SQL_COMMAND }}
   
+#     - name: Run API tests
+#       run: |
+#          newman run "${{ github.workspace }}/postman/collections/tests.json" -g "${{ github.workspace }}/postman/environments/globals.json" --bail
+#          if [ $? -ne 0 ]; then
+#           echo "Newman tests failed"
+#           exit 1
+#          fi
     - name: Run API tests
       run: |
-         newman run "${{ github.workspace }}/postman/collections/tests.json" -g "${{ github.workspace }}/postman/environments/globals.json" --bail
-         if [ $? -ne 0 ]; then
-          echo "Newman tests failed"
-          exit 1
-         fi
+          newman run "${{ github.workspace }}/postman/collections/tests.json" -g "${{ github.workspace }}/postman/environments/globals.json" --bail || exit 1
+
 #     - name: Run API tests
 #       run: |
 #           postman collection run "${{ github.workspace }}/postman/collections/tests.json" -e "20887326-37b84bc2-f993-415e-b8b0-c72f2e85e26e"
