Update apiTest.yaml

diff --git a/.github/workflows/apiTest.yaml b/.github/workflows/apiTest.yaml
--- a/.github/workflows/apiTest.yaml
+++ b/.github/workflows/apiTest.yaml
@@ -46,15 +46,22 @@ jobs:
         timeout 60 sh -c 'until nc -zv localhost 5000; do sleep 1; done'
     - name: Run logs 2
       run: docker-compose logs backend   
-  #  - name: Make REST request
-   #   run: |
-  #      curl -X GET http://localhost:5000/ping
+      
     - name: Install Newman
       run: npm install -g newman
 
     #- name: Run API tests
      # run: |
       #    postman collection run "${{ github.workspace }}/postman/collections/tests.json" -e "20887326-37b84bc2-f993-415e-b8b0-c72f2e85e26e" --integration-id "138020-${{ github.run_id }}" --bail
+    
+    - name: Setup tests Add new Organizer
+      run: |
+         newman run "${{ github.workspace }}/postman/collections/Create New Organizer For Tests.json" -g "${{ github.workspace }}/postman/environments/globals.json" --bail
+         if [ $? -ne 0 ]; then
+          echo "Newman tests failed"
+          exit 1
+         fi
+    
     - name: Run API tests
       run: |
          newman run "${{ github.workspace }}/postman/collections/tests.json" -g "${{ github.workspace }}/postman/environments/globals.json" --bail
